/*
 * This file is generated by jOOQ.
 */
package com.mycompany.jooq.model;


import com.mycompany.jooq.model.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = com.mycompany.jooq.model.tables.Users.USERS;
}
